#= require "jquery-1.7.2.min"
#= require "jquery.jplayer"
#= require "ttw-music-player"
#= require "player"
#= require "imagesloaded.min"
#= require "spin.min"
#= require "jquery.fitvids"
#= require "functions"
